services:
  tester:
    build: .
    ports:
      - "5007:5000"
    environment:
      MANIFEST: dataset/fr/nemo_manifest_ordered.json
      PATH_FROM: ./export/
      PATH_TO: ./dataset/
      FLAGGED: flagged.jsonl
    volumes:
      - ./dataset:/app/dataset:ro
      - ./flagged.jsonl:/app/flagged.jsonl
    restart: unless-stopped
