#!/usr/bin/env python3
"""Review-and-fix helper for dictionary terms carrying leaked metadata cruft.

The source dictionary extraction leaked trailing metadata into some term
fields ("MRP sigle angl. pour", "ankylose stapedo-vestibulaire l.f.", ...),
and part of those polluted the generated ASR sentences themselves. This tool
runs the drop-and-regenerate flow with minimal typing:

  python fix_suspect_terms.py extract
      Scan generated_dataset.jsonl for terms containing "sigle" or a dot,
      propose a cleaned term for each, and write suspect_terms_review.txt
      (tab-separated, vim-friendly, worst leakers first).

  python fix_suspect_terms.py apply            # dry run, prints the plan
  python fix_suspect_terms.py apply --apply    # actually writes
      Read the hand-edited review file and for every line still present:
      rename the term in the four dictionary input files, drop the term's
      rows from generated_dataset.jsonl, delete its clips on the SSD and its
      rows in the stage-06 state files. Ends by printing the exact commands
      that regenerate text, audio, manifests and QC for what was dropped.

Review file contract (lines starting with # are ignored):
    term_index<TAB>leaks/rows<TAB>score<TAB>current term<TAB>proposed term
  - delete a line (dd)        -> that term is left completely alone
  - keep a line               -> term renamed to the proposed term, rows and
                                 clips dropped, then regenerated by the
                                 printed commands
  - set proposed term to DROP -> term removed from the dataset for good
                                 (input rows deleted, nothing regenerated)
  Only the first and last columns are read back; the middle ones are context.
  The proposed term is editable: fix it before running apply if the
  automatic cleanup got the wording wrong. A trailing "# duplicates idx N"
  annotation (stripped by apply) flags that another input entry already
  carries that exact term, where DROP is usually the better call.

Stdlib only. Written with Claude Code.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent
REPO = BASE.parent

GENERATED = BASE / "generated_dataset.jsonl"
REVIEW_FILE = BASE / "suspect_terms_review.txt"
SCORED_NORMALIZED = BASE / "original_dictionnary.scored.normalized.jsonl"
# Every file of the input chain that carries the term, so they stay in sync
# (same set the earlier manual cruft fix edited, commit 2b1df28).
INPUT_FILES = [
    BASE / "original_dictionnary.jsonl",
    BASE / "original_dictionnary.normalized.jsonl",
    BASE / "original_dictionnary.scored.jsonl",
    SCORED_NORMALIZED,
]
AUDIO_DIR = REPO / "99_hf_release" / "data" / "dictionary"
STATE_FILES = [
    REPO / "06_hotfixes" / "improved" / "full.stt.jsonl",
    REPO / "06_hotfixes" / "improved" / "full.improved.jsonl",
]

# A term is suspect when the dictionary metadata marker may sit in it.
def is_suspect(term: str) -> bool:
    return "sigle" in term.lower() or "." in term


# The marker showing up inside a generated sentence: the word "sigle", an
# "angl." stub, letter-dot-letter-dot runs (n.f., l.m.p.), a bare "adj." or a
# stray standalone "l." token.
LEAK_RE = re.compile(
    r"\bsigle\b|\bangl\b\.?|[A-Za-zà-ÿ]\.[A-Za-zà-ÿ]\.|\badj\.|(?<=\s)l\.(?=\s|$)",
    re.IGNORECASE,
)

# Trailing metadata to strip: first cut everything from " sigle"/" acr" on,
# then peel the grammatical suffix family (n.f., l.m.p., adj., l.angl. pour,
# with stray spaces or doubled dots tolerated), then a sentence-final stray
# dot after a lowercase letter or digit. Lowercase on purpose so real dotted
# acronyms (A.O., B.T.P.S, E.F.R.) are never touched.
_SIGLE_TAIL = re.compile(r"\s+(?:sigle|acr)\b\.?.*$")
_SUFFIX_TAIL = re.compile(
    r"\s+(?:n|l|adj)\s*\.\s*(?:(?:[fmp]|angl)\s*\.?\s*)*(?:pour)?[\s.]*$"
)
_SPACED_DOT = re.compile(r"\s+\.$")
_SENTENCE_DOT = re.compile(r"(?<=[a-zà-ÿ0-9])\.$")


def clean_term(term: str) -> str:
    t = term
    stripped_marker = False
    for _ in range(4):
        prev = t
        t = _SIGLE_TAIL.sub("", t).rstrip(" ,")
        new = _SUFFIX_TAIL.sub("", t)
        if new != t:
            t = new.rstrip(" .")
        if t != prev:
            stripped_marker = True
        t = _SPACED_DOT.sub("", t)
        t = _SENTENCE_DOT.sub("", t)
        if t == prev:
            break
    # The unaccented English "gene" belongs to the leaked cruft ("LDHA gene
    # sigle angl. pour ..."); the earlier hand fix renamed those to the bare
    # symbol (BBS6, HRAS, ...), so follow that precedent, but only when a
    # marker was actually stripped.
    if stripped_marker and t.endswith(" gene"):
        t = t[: -len(" gene")]
    return t.strip() or term


def load_input_terms() -> dict[int, dict]:
    info: dict[int, dict] = {}
    with SCORED_NORMALIZED.open(encoding="utf-8") as fh:
        for line in fh:
            if line.strip():
                row = json.loads(line)
                info[row["index"]] = {"term": row["term"], "score": row.get("score")}
    return info


def cmd_extract() -> int:
    inputs = load_input_terms()
    groups: dict[int, dict] = {}
    with GENERATED.open(encoding="utf-8") as fh:
        for line in fh:
            if not line.strip():
                continue
            row = json.loads(line)
            term = row.get("term") or ""
            if not is_suspect(term):
                continue
            g = groups.setdefault(
                row["term_index"], {"term": term, "n_rows": 0, "n_leak": 0}
            )
            g["n_rows"] += 1
            if LEAK_RE.search(row.get("asr_training_target") or ""):
                g["n_leak"] += 1

    existing: dict[str, int] = {}
    for i, inp in inputs.items():
        existing.setdefault(inp["term"], i)

    lines = []
    unchanged = []
    for idx, g in groups.items():
        inp = inputs.get(idx)
        if inp is None:
            proposal = "DROP"  # input row already deleted upstream, rows are orphans
        elif inp["term"] != g["term"]:
            proposal = inp["term"]  # input already fixed by hand, trust it
        else:
            proposal = clean_term(g["term"])
            if proposal == g["term"]:
                unchanged.append(g["term"])
        other = existing.get(proposal)
        if other is not None and other != idx:
            proposal += f" # duplicates idx {other}"
        score = inp["score"] if inp else None
        lines.append(
            (
                -g["n_leak"],
                -g["n_rows"],
                g["term"],
                f"{idx}\t{g['n_leak']}/{g['n_rows']}\ts{score}\t{g['term']}\t{proposal}",
            )
        )
    lines.sort()

    with REVIEW_FILE.open("w", encoding="utf-8") as fh:
        fh.write("# suspect dictionary terms, worst leakers first\n")
        fh.write("# columns: term_index / leaking rows over rows / score / current term / PROPOSED term\n")
        fh.write("# dd a line = leave that term alone; keep = rename+regenerate;\n")
        fh.write("# set the last column to DROP = remove the term for good.\n")
        fh.write("# The last column is editable, fix the wording where the auto-strip is wrong.\n")
        fh.write("# A '# duplicates idx N' note means another input entry already has that exact\n")
        fh.write("# term: keeping the line generates the term twice, DROP is usually better there.\n")
        for _, _, _, text in lines:
            fh.write(text + "\n")

    print(f"wrote {REVIEW_FILE} ({len(lines)} terms)")
    print(f"terms whose proposal is unchanged (need a manual edit or a dd): {len(unchanged)}")
    for t in unchanged:
        print(f"  {t!r}")
    return 0


def parse_review() -> dict[int, tuple[str, str]]:
    if not REVIEW_FILE.exists():
        sys.exit(f"{REVIEW_FILE} not found, run extract first")
    picked: dict[int, tuple[str, str]] = {}
    for n, raw in enumerate(REVIEW_FILE.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.rstrip("\n")
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 5:
            sys.exit(f"{REVIEW_FILE}:{n}: expected 5 tab-separated columns, got {len(parts)}")
        try:
            idx = int(parts[0])
        except ValueError:
            sys.exit(f"{REVIEW_FILE}:{n}: bad term_index {parts[0]!r}")
        if idx in picked:
            sys.exit(f"{REVIEW_FILE}:{n}: duplicate term_index {idx}")
        old, new = parts[3], parts[4].split(" # ")[0].strip()
        if not new:
            sys.exit(f"{REVIEW_FILE}:{n}: empty proposed term (use DROP to delete)")
        picked[idx] = (old, new)
    if not picked:
        sys.exit("review file has no data lines left, nothing to do")
    return picked


def rewrite_jsonl(path: Path, transform, do_apply: bool) -> int:
    """Stream path through transform(line_dict) -> None (drop) / dict (replace)
    / ... (keep verbatim). Returns the number of dropped+changed lines."""
    changed = 0
    tmp = path.with_suffix(path.suffix + ".tmp")
    with path.open(encoding="utf-8") as src, tmp.open("w", encoding="utf-8") as dst:
        for line in src:
            if not line.strip():
                dst.write(line)
                continue
            row = json.loads(line)
            out = transform(row)
            if out is None:
                changed += 1
                continue
            if out is Ellipsis:
                dst.write(line)
            else:
                changed += 1
                dst.write(json.dumps(out, ensure_ascii=False) + "\n")
    if do_apply:
        os.replace(tmp, path)
    else:
        tmp.unlink()
    return changed


def cmd_apply(do_apply: bool, skip_audio: bool) -> int:
    picked = parse_review()
    inputs = load_input_terms()

    # Classify every reviewed term against the current input state.
    renames: dict[int, str] = {}
    drops: set[int] = set()
    skipped: dict[int, str] = {}
    for idx, (old, new) in sorted(picked.items()):
        cur = inputs.get(idx, {}).get("term")
        if new == "DROP":
            drops.add(idx)
        elif cur == new:
            pass  # input already clean (fixed earlier), rows still need dropping
        elif cur == old:
            renames[idx] = new
        else:
            skipped[idx] = f"  idx {idx}: input says {cur!r}, review says {old!r} -> {new!r}"
    acted = set(picked) - set(skipped)
    if skipped:
        print(f"SKIPPING {len(skipped)} term(s) whose input no longer matches the review file:")
        print("\n".join(skipped.values()))

    # Warn about rename collisions with terms that already exist elsewhere.
    existing = {}
    for i, inp in inputs.items():
        existing.setdefault(inp["term"], i)
    for idx, new in renames.items():
        other = existing.get(new)
        if other is not None and other != idx:
            print(f"note: idx {idx} renamed to {new!r} which already exists at idx {other} (dedup will handle identical variants)")

    mode = "APPLY" if do_apply else "DRY RUN"
    print(f"\n== {mode}: {len(acted)} term(s): {len(renames)} rename, {len(drops)} DROP, "
          f"{len(acted) - len(renames) - len(drops)} rows-only ==")

    # 1. input files: rename or delete the term rows.
    for path in INPUT_FILES:
        def fix(row, _renames=renames, _drops=drops):
            idx = row.get("index")
            if idx in _drops:
                return None
            if idx in _renames and row.get("term") != _renames[idx]:
                row["term"] = _renames[idx]
                return row
            return Ellipsis
        n = rewrite_jsonl(path, fix, do_apply)
        print(f"{path.name}: {n} row(s) {'updated' if do_apply else 'would update'}")

    # 2. generated rows: drop everything for the acted indices.
    def drop_rows(row):
        return None if row.get("term_index") in acted else Ellipsis
    n = rewrite_jsonl(GENERATED, drop_rows, do_apply)
    print(f"{GENERATED.name}: {n} row(s) {'dropped' if do_apply else 'would drop'}")

    # 3. clips on the SSD.
    prefixes = tuple(f"{idx:06d}_" for idx in acted)
    if skip_audio:
        print("clip deletion skipped (--skip-audio)")
    elif not AUDIO_DIR.is_dir():
        sys.exit(f"{AUDIO_DIR} not reachable (SSD unmounted?): mount it or pass --skip-audio")
    else:
        clips = [p for p in AUDIO_DIR.iterdir() if p.name.startswith(prefixes)]
        print(f"{AUDIO_DIR}: {len(clips)} clip(s) {'deleted' if do_apply else 'would delete'}")
        if do_apply:
            for p in clips:
                p.unlink()

    # 4. stage-06 state rows for those clips.
    for path in STATE_FILES:
        if not path.exists():
            print(f"{path} missing, skipped")
            continue
        def drop_state(row):
            ap = row.get("audio_filepath") or ""
            if "dictionary" in ap and Path(ap).name.startswith(prefixes):
                return None
            return Ellipsis
        n = rewrite_jsonl(path, drop_state, do_apply)
        print(f"{path.relative_to(REPO)}: {n} row(s) {'dropped' if do_apply else 'would drop'}")

    if not do_apply:
        print("\ndry run only, re-run with --apply to write.")
    print(REGEN_COMMANDS)
    return 0


REGEN_COMMANDS = """
== regeneration commands (run in this order) ==
# 1. texts (resumes: only the dropped indices are regenerated; needs OPENROUTER_API_KEY)
cd 01_dictionnary
uv run 03_generate_texts.py --n-variants '{"0-1":2,"2-3":4,"4":5,"5":6,"6":7,"7":8,"8-10":11}' --n-jobs 32

# 2. audio (voxtral TTS server up first; resumable, existing clips skip)
cd ../05_generate_audio
uv run 01_generate_audio.py --check
uv run 01_generate_audio.py --input ../01_dictionnary/generated_dataset.jsonl --output ../99_hf_release/data/dictionary

# 3. manifests (so stage 06 sees the new clips)
cd ../99_hf_release
uv run 01_build_nemo_manifest.py --input ../01_dictionnary/generated_dataset.jsonl --audio-dir data/dictionary --name dictionary
uv run 02_combine_nemo_manifests.py

# 4. QC the new clips (alternating stt/tts improvement)
cd ../06_hotfixes
sudo -E CATEGORY="dictionary" ./driver.sh

# 5. carry QC results into the manifests (then rebuild parquet whenever you release)
cd ../99_hf_release
uv run 03_sync_hotfix_results.py --apply
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("extract", help="write the vim review file")
    p_apply = sub.add_parser("apply", help="execute the edited review file")
    p_apply.add_argument("--apply", action="store_true", help="actually write (default: dry run)")
    p_apply.add_argument("--skip-audio", action="store_true",
                         help="do not touch the SSD clips (e.g. SSD not mounted)")
    args = ap.parse_args()
    if args.cmd == "extract":
        return cmd_extract()
    return cmd_apply(args.apply, args.skip_audio)


if __name__ == "__main__":
    raise SystemExit(main())
